# Generated by Django 4.1.7 on 2023-03-12 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Активно ищу работу'), (2, 'Рассматриваю предложения'), (3, 'Архив')], default=1, verbose_name='Статус')),
                ('grade', models.CharField(max_length=50, verbose_name='Уровень резюме')),
                ('specialty', models.CharField(max_length=50, verbose_name='Специальность')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('education', models.CharField(max_length=50, verbose_name='Образование')),
                ('experience', models.TextField(verbose_name='Опыт')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='Портфолио')),
                ('title', models.CharField(max_length=35, verbose_name='Название')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
